// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calpb/calcu.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0213d933d4ccb9, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumRespone struct {
	SumResult            int32    `protobuf:"varint,1,opt,name=sum_result,json=sumResult,proto3" json:"sum_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRespone) Reset()         { *m = SumRespone{} }
func (m *SumRespone) String() string { return proto.CompactTextString(m) }
func (*SumRespone) ProtoMessage()    {}
func (*SumRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0213d933d4ccb9, []int{1}
}

func (m *SumRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRespone.Unmarshal(m, b)
}
func (m *SumRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRespone.Marshal(b, m, deterministic)
}
func (m *SumRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRespone.Merge(m, src)
}
func (m *SumRespone) XXX_Size() int {
	return xxx_messageInfo_SumRespone.Size(m)
}
func (m *SumRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRespone.DiscardUnknown(m)
}

var xxx_messageInfo_SumRespone proto.InternalMessageInfo

func (m *SumRespone) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calcu.SumRequest")
	proto.RegisterType((*SumRespone)(nil), "calcu.SumRespone")
}

func init() { proto.RegisterFile("calpb/calcu.proto", fileDescriptor_2c0213d933d4ccb9) }

var fileDescriptor_2c0213d933d4ccb9 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xc1, 0x8a, 0xc2, 0x30,
	0x10, 0x86, 0xb7, 0xbb, 0x74, 0x61, 0x67, 0xbb, 0x0b, 0xcd, 0x49, 0x04, 0x41, 0xeb, 0x45, 0x10,
	0x2b, 0xe8, 0x1b, 0xd4, 0xbb, 0x87, 0xd6, 0x93, 0x97, 0xd2, 0xc4, 0x11, 0x0a, 0x49, 0x13, 0x93,
	0x8c, 0xcf, 0x2f, 0xa6, 0x55, 0xf1, 0x38, 0xdf, 0xfc, 0xfc, 0xf3, 0x0d, 0xa4, 0xa2, 0x91, 0x86,
	0xaf, 0x45, 0x23, 0x05, 0xe5, 0xc6, 0x6a, 0xaf, 0x59, 0x1c, 0x86, 0xec, 0x00, 0x50, 0x91, 0x2a,
	0xf1, 0x42, 0xe8, 0x3c, 0x9b, 0x41, 0x72, 0x6e, 0xad, 0xf3, 0x75, 0x47, 0x8a, 0xa3, 0x1d, 0x45,
	0xd3, 0x68, 0x11, 0x97, 0xbf, 0x81, 0xed, 0x03, 0x62, 0x73, 0xf8, 0x73, 0x28, 0x74, 0x77, 0x7a,
	0x64, 0x3e, 0x43, 0x26, 0xe9, 0x61, 0x1f, 0xca, 0x96, 0x43, 0xab, 0x33, 0xba, 0x43, 0x36, 0x01,
	0x70, 0xa4, 0x6a, 0x8b, 0x8e, 0xa4, 0x1f, 0x3a, 0x7f, 0x5c, 0xd8, 0x93, 0xf4, 0x9b, 0x02, 0xd2,
	0xdd, 0xdd, 0x45, 0x36, 0x5e, 0xdb, 0x0a, 0xed, 0xb5, 0x15, 0xc8, 0x56, 0xf0, 0x55, 0x91, 0x62,
	0x69, 0xde, 0x3b, 0xbf, 0x1c, 0xc7, 0x6f, 0x28, 0x1c, 0xc8, 0x3e, 0x8a, 0xff, 0x63, 0x22, 0x9e,
	0x1d, 0x86, 0xf3, 0xef, 0xf0, 0xe4, 0xf6, 0x16, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xcb, 0x3c, 0xa2,
	0xf9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumRespone, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumRespone, error) {
	out := new(SumRespone)
	err := c.cc.Invoke(ctx, "/calcu.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumRespone, error)
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calcu.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calcu.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calpb/calcu.proto",
}
