// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Calculator/calpb/calcu.proto

package calpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SumRequest struct {
	FirstNumber          int32    `protobuf:"varint,1,opt,name=first_number,json=firstNumber,proto3" json:"first_number,omitempty"`
	SecondNumber         int32    `protobuf:"varint,2,opt,name=second_number,json=secondNumber,proto3" json:"second_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumRespone struct {
	SumResult            int32    `protobuf:"varint,1,opt,name=sum_result,json=sumResult,proto3" json:"sum_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRespone) Reset()         { *m = SumRespone{} }
func (m *SumRespone) String() string { return proto.CompactTextString(m) }
func (*SumRespone) ProtoMessage()    {}
func (*SumRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{1}
}

func (m *SumRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRespone.Unmarshal(m, b)
}
func (m *SumRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRespone.Marshal(b, m, deterministic)
}
func (m *SumRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRespone.Merge(m, src)
}
func (m *SumRespone) XXX_Size() int {
	return xxx_messageInfo_SumRespone.Size(m)
}
func (m *SumRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRespone.DiscardUnknown(m)
}

var xxx_messageInfo_SumRespone proto.InternalMessageInfo

func (m *SumRespone) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type SumManyRequest struct {
	K                    int32    `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	N                    int32    `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumManyRequest) Reset()         { *m = SumManyRequest{} }
func (m *SumManyRequest) String() string { return proto.CompactTextString(m) }
func (*SumManyRequest) ProtoMessage()    {}
func (*SumManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{2}
}

func (m *SumManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumManyRequest.Unmarshal(m, b)
}
func (m *SumManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumManyRequest.Marshal(b, m, deterministic)
}
func (m *SumManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumManyRequest.Merge(m, src)
}
func (m *SumManyRequest) XXX_Size() int {
	return xxx_messageInfo_SumManyRequest.Size(m)
}
func (m *SumManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumManyRequest proto.InternalMessageInfo

func (m *SumManyRequest) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

func (m *SumManyRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type SumManyRespone struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumManyRespone) Reset()         { *m = SumManyRespone{} }
func (m *SumManyRespone) String() string { return proto.CompactTextString(m) }
func (*SumManyRespone) ProtoMessage()    {}
func (*SumManyRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{3}
}

func (m *SumManyRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumManyRespone.Unmarshal(m, b)
}
func (m *SumManyRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumManyRespone.Marshal(b, m, deterministic)
}
func (m *SumManyRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumManyRespone.Merge(m, src)
}
func (m *SumManyRespone) XXX_Size() int {
	return xxx_messageInfo_SumManyRespone.Size(m)
}
func (m *SumManyRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_SumManyRespone.DiscardUnknown(m)
}

var xxx_messageInfo_SumManyRespone proto.InternalMessageInfo

func (m *SumManyRespone) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SumLongRequest struct {
	N                    int32    `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumLongRequest) Reset()         { *m = SumLongRequest{} }
func (m *SumLongRequest) String() string { return proto.CompactTextString(m) }
func (*SumLongRequest) ProtoMessage()    {}
func (*SumLongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{4}
}

func (m *SumLongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumLongRequest.Unmarshal(m, b)
}
func (m *SumLongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumLongRequest.Marshal(b, m, deterministic)
}
func (m *SumLongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumLongRequest.Merge(m, src)
}
func (m *SumLongRequest) XXX_Size() int {
	return xxx_messageInfo_SumLongRequest.Size(m)
}
func (m *SumLongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumLongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumLongRequest proto.InternalMessageInfo

func (m *SumLongRequest) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type SumLongRespone struct {
	LongResult           float64  `protobuf:"fixed64,1,opt,name=long_result,json=longResult,proto3" json:"long_result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumLongRespone) Reset()         { *m = SumLongRespone{} }
func (m *SumLongRespone) String() string { return proto.CompactTextString(m) }
func (*SumLongRespone) ProtoMessage()    {}
func (*SumLongRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_41636d21e3a09d0c, []int{5}
}

func (m *SumLongRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumLongRespone.Unmarshal(m, b)
}
func (m *SumLongRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumLongRespone.Marshal(b, m, deterministic)
}
func (m *SumLongRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumLongRespone.Merge(m, src)
}
func (m *SumLongRespone) XXX_Size() int {
	return xxx_messageInfo_SumLongRespone.Size(m)
}
func (m *SumLongRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_SumLongRespone.DiscardUnknown(m)
}

var xxx_messageInfo_SumLongRespone proto.InternalMessageInfo

func (m *SumLongRespone) GetLongResult() float64 {
	if m != nil {
		return m.LongResult
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calcu.SumRequest")
	proto.RegisterType((*SumRespone)(nil), "calcu.SumRespone")
	proto.RegisterType((*SumManyRequest)(nil), "calcu.SumManyRequest")
	proto.RegisterType((*SumManyRespone)(nil), "calcu.SumManyRespone")
	proto.RegisterType((*SumLongRequest)(nil), "calcu.SumLongRequest")
	proto.RegisterType((*SumLongRespone)(nil), "calcu.SumLongRespone")
}

func init() { proto.RegisterFile("Calculator/calpb/calcu.proto", fileDescriptor_41636d21e3a09d0c) }

var fileDescriptor_41636d21e3a09d0c = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4b, 0x4b, 0xc4, 0x30,
	0x10, 0xc7, 0x8d, 0xd2, 0x5d, 0x9c, 0xad, 0xc2, 0x06, 0x14, 0x29, 0x3e, 0xe3, 0xa5, 0xa0, 0xae,
	0xaf, 0xa3, 0x37, 0xbd, 0x6a, 0x0f, 0xad, 0x27, 0x2f, 0x4b, 0x5b, 0xe3, 0xb2, 0x6c, 0x9a, 0xd4,
	0x3c, 0x04, 0xbf, 0x9b, 0x1f, 0x4e, 0x9a, 0xa4, 0x34, 0xcb, 0x5e, 0x02, 0xf3, 0x9f, 0xff, 0xfc,
	0x32, 0x33, 0x0c, 0x1c, 0xbf, 0x94, 0xac, 0x36, 0xac, 0xd4, 0x42, 0xde, 0xd6, 0x25, 0x6b, 0xab,
	0xee, 0xad, 0xcd, 0xac, 0x95, 0x42, 0x0b, 0x1c, 0xd9, 0x80, 0xbc, 0x03, 0x14, 0xa6, 0xc9, 0xe9,
	0xb7, 0xa1, 0x4a, 0xe3, 0x0b, 0x88, 0xbf, 0x96, 0x52, 0xe9, 0x39, 0x37, 0x4d, 0x45, 0xe5, 0x11,
	0x3a, 0x47, 0x69, 0x94, 0x4f, 0xac, 0x96, 0x59, 0x09, 0x5f, 0xc2, 0x9e, 0xa2, 0xb5, 0xe0, 0x9f,
	0xbd, 0x67, 0xdb, 0x7a, 0x62, 0x27, 0x3a, 0x13, 0xb9, 0xf2, 0x54, 0xd5, 0x0a, 0x4e, 0xf1, 0x09,
	0x80, 0x32, 0xcd, 0x5c, 0x52, 0x65, 0x98, 0xf6, 0xcc, 0x5d, 0x65, 0xf3, 0x86, 0x69, 0x72, 0x0d,
	0xfb, 0x85, 0x69, 0xde, 0x4a, 0xfe, 0xdb, 0xb7, 0x11, 0x03, 0x5a, 0x79, 0x1f, 0x5a, 0x75, 0x51,
	0xe6, 0x7f, 0x41, 0x19, 0x49, 0x03, 0xb7, 0xc3, 0x1f, 0xc2, 0x68, 0x0d, 0xed, 0x23, 0x72, 0x6a,
	0x9d, 0xaf, 0x82, 0x2f, 0x02, 0x6e, 0xd6, 0x73, 0x33, 0x72, 0x1f, 0xe4, 0x1d, 0xe9, 0x0c, 0x26,
	0x4c, 0xf0, 0x45, 0xd8, 0x29, 0xca, 0x81, 0x39, 0x87, 0x61, 0xfa, 0xe1, 0x0f, 0xc1, 0x74, 0xd8,
	0x6a, 0x41, 0xe5, 0xcf, 0xb2, 0xa6, 0xf8, 0x06, 0x76, 0x0a, 0xd3, 0xe0, 0xe9, 0xcc, 0xed, 0x77,
	0xd8, 0x67, 0xb2, 0x26, 0xd9, 0x3f, 0xc8, 0x16, 0x7e, 0x82, 0xb1, 0x9f, 0x00, 0x1f, 0x0c, 0xf9,
	0x60, 0xfe, 0x64, 0x43, 0xf6, 0xa5, 0x77, 0xc8, 0x17, 0x77, 0x4d, 0x87, 0xc5, 0xc1, 0x90, 0xc9,
	0x86, 0xec, 0x8b, 0x53, 0xf4, 0x3c, 0xfe, 0x88, 0xec, 0x21, 0x54, 0x23, 0x7b, 0x03, 0x8f, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x84, 0x4a, 0x85, 0x4f, 0x23, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumRespone, error)
	SumMany(ctx context.Context, in *SumManyRequest, opts ...grpc.CallOption) (CalculatorService_SumManyClient, error)
	SumLong(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumLongClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumRespone, error) {
	out := new(SumRespone)
	err := c.cc.Invoke(ctx, "/calcu.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) SumMany(ctx context.Context, in *SumManyRequest, opts ...grpc.CallOption) (CalculatorService_SumManyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calcu.CalculatorService/SumMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceSumManyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_SumManyClient interface {
	Recv() (*SumManyRespone, error)
	grpc.ClientStream
}

type calculatorServiceSumManyClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceSumManyClient) Recv() (*SumManyRespone, error) {
	m := new(SumManyRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) SumLong(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumLongClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[1], "/calcu.CalculatorService/SumLong", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceSumLongClient{stream}
	return x, nil
}

type CalculatorService_SumLongClient interface {
	Send(*SumLongRequest) error
	CloseAndRecv() (*SumLongRespone, error)
	grpc.ClientStream
}

type calculatorServiceSumLongClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceSumLongClient) Send(m *SumLongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceSumLongClient) CloseAndRecv() (*SumLongRespone, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SumLongRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumRespone, error)
	SumMany(*SumManyRequest, CalculatorService_SumManyServer) error
	SumLong(CalculatorService_SumLongServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *SumRequest) (*SumRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServiceServer) SumMany(req *SumManyRequest, srv CalculatorService_SumManyServer) error {
	return status.Errorf(codes.Unimplemented, "method SumMany not implemented")
}
func (*UnimplementedCalculatorServiceServer) SumLong(srv CalculatorService_SumLongServer) error {
	return status.Errorf(codes.Unimplemented, "method SumLong not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calcu.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_SumMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SumManyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).SumMany(m, &calculatorServiceSumManyServer{stream})
}

type CalculatorService_SumManyServer interface {
	Send(*SumManyRespone) error
	grpc.ServerStream
}

type calculatorServiceSumManyServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceSumManyServer) Send(m *SumManyRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_SumLong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).SumLong(&calculatorServiceSumLongServer{stream})
}

type CalculatorService_SumLongServer interface {
	SendAndClose(*SumLongRespone) error
	Recv() (*SumLongRequest, error)
	grpc.ServerStream
}

type calculatorServiceSumLongServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceSumLongServer) SendAndClose(m *SumLongRespone) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceSumLongServer) Recv() (*SumLongRequest, error) {
	m := new(SumLongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calcu.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumMany",
			Handler:       _CalculatorService_SumMany_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SumLong",
			Handler:       _CalculatorService_SumLong_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "Calculator/calpb/calcu.proto",
}
